repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args:
          - --settings-path=.isort.cfg
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - --maxkb=1024
      - id: check-merge-conflict
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
      - id: debug-statements
  - repo: local
    hooks:
      - id: check-extension
        name: Check Ipynb
        args:
          - ipynb
        entry: ./scripts/check_extension.sh
        language: script
      - id: dockerfile-lint
        name: Lint Dockerfile
        entry: ./scripts/hadolint.sh
        language: system
        files: .*Dockerfile.*$
        pass_filenames: true
      - id: validate-commit-msg
        name: Commit Message is Valid
        args:
          - --negate
        entry: ^(build|ci|docs|feat|fix|perf|refactor|style|test|revert|hotfix|ops|chore)\([\w,\.,\-,\(,\),\/]+\)(!?)(:)\s{1}([\w,\W,:]+)$
        language: pygrep
        stages:
          - commit-msg
